jobs:

- job: OpenJDK8
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: |
      set -ev
      curl -O -L --retry 3 https://github.com/sormuras/bach/raw/master/install-jdk.sh
      source install-jdk.sh --url https://cdn.azul.com/zulu/bin/zulu8.38.0.13-ca-jdk8.0.212-linux_x64.tar.gz
      ./gradlew --no-daemon --version
      ./gradlew --no-daemon clean test verifyPlugin
    displayName: Build
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: build/test-results/test/TEST-*.xml
    condition: succeededOrFailed()
